logs/2018-02-20-cli-wg-initial-meeting.log

Notes of the first CLI WG meeting. Closes #1. Thanks!

first meeting notes

---

logs/2018-02-20-cli-wg-initial-meeting.log

Removes a lot of the pats/joins, +1's, etc. To condense to just important notes. I left a `...` where all the messages were removed so people can look in the git history if they'd like to see the raw logs.

Removes auxillary messages

---

CODE_OF_CONDUCT.md
README.md

This adds a bit more information to the Readme.
It also tries to settle #3 and #4, and I'd love to get some feedback specifically on that!
This PR also copies the Rust CoC into this repo.

Readme upgrade

---

logs/2018-03-09-cli-wg-meeting.log

Notes for the second meeting. Closes https://github.com/rust-lang-nursery/cli-wg/issues/16. Thanks!

second meeting notes

---

logs/2018-05-03-packaging.log
logs/2018-05-03-packaging.md

Attendees: @epage, @killercup, @ashleygwilliams, @kornelski, @Dylan-DPC
Interested parties: @mmstick, @Aaronepower, @volks73, @wdv4758h, @cardoe.

2018-05-03-packaging meeting log and summary

---

src/tutorial/errors.md

Not meant to replace the book chapter, just wants to provide an
alternative perspective on this in the context of CLI apps.

Tutorial: Errors draft

---

src/in-depth/human-communication.md

Adds a section about how to talk to humans (it's hard!)

Adding writing style for humans

---

src/in-depth/human-communication.md

This adds a section with advice on things to keep in mind when writing logging code (#75)

Adding a section about writing log messages

---

src/tutorial/output.md

Explaining stdout vs stderr

---

src/in-depth/config-files.md

This is probably the most WIP right now.
It mentions `confy` directly and has some work left to do for discovering, promoting or finishing other crates

Adding a section about configuration files

---

src/in-depth/docs.md

Draft chapter about documentation with man

---

src/tutorial/output.md

because https://twitter.com/steveklabnik/status/1042454785960620032

Book: Mention stdout().lock()

---

src/tutorial/cli-args.md

This should make this work right now for readers while clap3 is not yet released.

Book: Use structopt for now

---

src/tutorial/testing.md

Book: First draft of Integration testing

---

src/tutorial/packaging.md

Book: Packaging

---

src/in-depth/machine-communication.md

Book: Start machine communication chapter

---

src/in-depth/exit-code.md
src/tutorial/README.md
src/tutorial/setup.md
src/tutorial/testing.md

Fixes a few outdated links, mostly related to the new structure of the rust web page.

Update outdated links

---

src/tutorial/testing.md
src/tutorial/testing/src/main.rs

Thanks @dkotrada for making me aware of this!

Book: Explain usage of traits in testing chapter

---

src/in-depth/docs.md

Mention `clap_generate` is for alpha clap v3

---

src/tutorial/output.md

https://github.com/rust-lang-nursery/cli-wg/issues/118

Add example of setting env vars in PowerShell

---

src/tutorial/testing.md

fixed typo

---

src/tutorial/errors.md

Nothing ground breaking, but I think this sounds better.

Minor grammar improvement.

---

src/tutorial/testing.md

closes https://github.com/rust-lang-nursery/cli-wg/issues/140

Fix fuzzing broken link

---

src/tutorial/errors.md

Add missing "the"; use "it would" instead of contraction "it'd".

Fix typo and style

---

src/tutorial/cli-args.md

Make it clear source is edited in src/main.rs and where source parts are positioned.
Help newbies by claryfying this.

Clarify source position
